jQuery('.owl-carousel').owlCarousel({
   loop:true,
    margin:0,
    nav:true,
    animateOut: 'fadeOut',
    autoplayTimeout:5000,
    autoplay:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})